#!/bin/bash

DEFAULT_QUERY="trashed = false and 'me' in owners"
GDRIVE_CMD="gdrive"

function color_msg
{
  echo -e $3 "\033[$1m$2\033[0m"
}

# find_fid FILE_NAME
function find_fid()
{
  ${GDRIVE_CMD} list -q "${DEFAULT_QUERY} and name = \"$1\"" | \
  sed -n '1!p' | \
  awk -F " " {'print $1'}
}

# del_old_file FILE_NAME
function del_old_file()
{
  ${GDRIVE_CMD} delete ${fid} > /dev/null 2>&1
}

function only_one_target()
{
  if [ $# -gt 1 ]; then
    return 1
  else
    return 0
  fi
}

function get_parend_id()
{
  ${GDRIVE_CMD} info $1 | grep Parents | awk -F " " {'print $2'}
}

# upload_file SRC_FILE_PATH TARGET_FID
function upload_file()
{
  local parend_id=$(get_parend_id ${2})
  echo "fid: $2"
  echo "pid: ${parend_id}"
  ${GDRIVE_CMD} delete ${2}
  ${GDRIVE_CMD} upload -r -p ${parend_id} "${1}"
}

function to_array()
{
  local i=1
  for element in $1; do
    array[$i]=${element}
    i=$(( $i + 1 ))
  done
}

function show_path()
{
  local path=$(${GDRIVE_CMD} info $2 | grep Path | awk -F ": " {'print $2'})
  echo -e "$1 ${path}"
}

function select_one_target()
{
  echo -e
  echo -e "We found multiple files with the same file name: "
  local i=1
  for fid in $1; do
    show_path $i ${fid}
    i=$(( $i + 1 ))
  done

  echo -e
  echo -ne "Which one you want to replace? [1] "
  read select
  select=${select:-1}
  to_array "$1"
  selected_fid=${array[$select]}
}

function sync_file()
{
  local src_file="$1"
  local file_name="$(basename "${src_file}")"
  echo -e
  echo -ne "Syncing "
  color_msg 33 "${file_name}" -n
  echo -ne " ... "
  local fids="$(find_fid "${file_name}")"

  if only_one_target $fids; then
    upload_file "${src_file}" "${fids}" > /dev/null 2>&1
  else
    select_one_target "${fids}"
    upload_file "${src_file}" "${selected_fid}" > /dev/null 2>&1
  fi

  color_msg 32 "Done"
}

if [ $# -eq 0 ]; then
  echo -e
  echo -e "Usage: gdsync FILE_PATH1 [FILE_PATH2]"
  echo -e
  echo -e
  exit 0
fi

for f in "$@"; do
  sync_file "${f}"
done
